# Generated by Django 5.1.5 on 2025-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='фотография'),
        ),
    ]
